// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"fyp/food-rs/internal/interfaces"

	mock "github.com/stretchr/testify/mock"
)

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

type AuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthService) EXPECT() *AuthService_Expecter {
	return &AuthService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type AuthService
func (_mock *AuthService) Login(ctx context.Context, input interfaces.LoginInput) (*interfaces.AuthResult, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *interfaces.AuthResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.LoginInput) (*interfaces.AuthResult, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.LoginInput) *interfaces.AuthResult); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.AuthResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interfaces.LoginInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - input interfaces.LoginInput
func (_e *AuthService_Expecter) Login(ctx interface{}, input interface{}) *AuthService_Login_Call {
	return &AuthService_Login_Call{Call: _e.mock.On("Login", ctx, input)}
}

func (_c *AuthService_Login_Call) Run(run func(ctx context.Context, input interfaces.LoginInput)) *AuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interfaces.LoginInput
		if args[1] != nil {
			arg1 = args[1].(interfaces.LoginInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthService_Login_Call) Return(authResult *interfaces.AuthResult, err error) *AuthService_Login_Call {
	_c.Call.Return(authResult, err)
	return _c
}

func (_c *AuthService_Login_Call) RunAndReturn(run func(ctx context.Context, input interfaces.LoginInput) (*interfaces.AuthResult, error)) *AuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type AuthService
func (_mock *AuthService) Logout(ctx context.Context, rawRefreshToken string) error {
	ret := _mock.Called(ctx, rawRefreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, rawRefreshToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type AuthService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - rawRefreshToken string
func (_e *AuthService_Expecter) Logout(ctx interface{}, rawRefreshToken interface{}) *AuthService_Logout_Call {
	return &AuthService_Logout_Call{Call: _e.mock.On("Logout", ctx, rawRefreshToken)}
}

func (_c *AuthService_Logout_Call) Run(run func(ctx context.Context, rawRefreshToken string)) *AuthService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthService_Logout_Call) Return(err error) *AuthService_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthService_Logout_Call) RunAndReturn(run func(ctx context.Context, rawRefreshToken string) error) *AuthService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function for the type AuthService
func (_mock *AuthService) Refresh(ctx context.Context, rawRefreshToken string) (*interfaces.AuthResult, error) {
	ret := _mock.Called(ctx, rawRefreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 *interfaces.AuthResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*interfaces.AuthResult, error)); ok {
		return returnFunc(ctx, rawRefreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *interfaces.AuthResult); ok {
		r0 = returnFunc(ctx, rawRefreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.AuthResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, rawRefreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthService_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type AuthService_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - rawRefreshToken string
func (_e *AuthService_Expecter) Refresh(ctx interface{}, rawRefreshToken interface{}) *AuthService_Refresh_Call {
	return &AuthService_Refresh_Call{Call: _e.mock.On("Refresh", ctx, rawRefreshToken)}
}

func (_c *AuthService_Refresh_Call) Run(run func(ctx context.Context, rawRefreshToken string)) *AuthService_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthService_Refresh_Call) Return(authResult *interfaces.AuthResult, err error) *AuthService_Refresh_Call {
	_c.Call.Return(authResult, err)
	return _c
}

func (_c *AuthService_Refresh_Call) RunAndReturn(run func(ctx context.Context, rawRefreshToken string) (*interfaces.AuthResult, error)) *AuthService_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type AuthService
func (_mock *AuthService) Register(ctx context.Context, input interfaces.RegisterInput) (*interfaces.AuthResult, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *interfaces.AuthResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.RegisterInput) (*interfaces.AuthResult, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.RegisterInput) *interfaces.AuthResult); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.AuthResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interfaces.RegisterInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type AuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - input interfaces.RegisterInput
func (_e *AuthService_Expecter) Register(ctx interface{}, input interface{}) *AuthService_Register_Call {
	return &AuthService_Register_Call{Call: _e.mock.On("Register", ctx, input)}
}

func (_c *AuthService_Register_Call) Run(run func(ctx context.Context, input interfaces.RegisterInput)) *AuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interfaces.RegisterInput
		if args[1] != nil {
			arg1 = args[1].(interfaces.RegisterInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthService_Register_Call) Return(authResult *interfaces.AuthResult, err error) *AuthService_Register_Call {
	_c.Call.Return(authResult, err)
	return _c
}

func (_c *AuthService_Register_Call) RunAndReturn(run func(ctx context.Context, input interfaces.RegisterInput) (*interfaces.AuthResult, error)) *AuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}
