// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"fyp/food-rs/internal/interfaces"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewCatalogService creates a new instance of CatalogService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCatalogService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CatalogService {
	mock := &CatalogService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CatalogService is an autogenerated mock type for the CatalogService type
type CatalogService struct {
	mock.Mock
}

type CatalogService_Expecter struct {
	mock *mock.Mock
}

func (_m *CatalogService) EXPECT() *CatalogService_Expecter {
	return &CatalogService_Expecter{mock: &_m.Mock}
}

// CreateGeneratedMeal provides a mock function for the type CatalogService
func (_mock *CatalogService) CreateGeneratedMeal(ctx context.Context, input interfaces.GeneratedCatalogMealInput) (interfaces.CatalogMeal, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateGeneratedMeal")
	}

	var r0 interfaces.CatalogMeal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.GeneratedCatalogMealInput) (interfaces.CatalogMeal, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.GeneratedCatalogMealInput) interfaces.CatalogMeal); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(interfaces.CatalogMeal)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interfaces.GeneratedCatalogMealInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CatalogService_CreateGeneratedMeal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGeneratedMeal'
type CatalogService_CreateGeneratedMeal_Call struct {
	*mock.Call
}

// CreateGeneratedMeal is a helper method to define mock.On call
//   - ctx context.Context
//   - input interfaces.GeneratedCatalogMealInput
func (_e *CatalogService_Expecter) CreateGeneratedMeal(ctx interface{}, input interface{}) *CatalogService_CreateGeneratedMeal_Call {
	return &CatalogService_CreateGeneratedMeal_Call{Call: _e.mock.On("CreateGeneratedMeal", ctx, input)}
}

func (_c *CatalogService_CreateGeneratedMeal_Call) Run(run func(ctx context.Context, input interfaces.GeneratedCatalogMealInput)) *CatalogService_CreateGeneratedMeal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interfaces.GeneratedCatalogMealInput
		if args[1] != nil {
			arg1 = args[1].(interfaces.GeneratedCatalogMealInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CatalogService_CreateGeneratedMeal_Call) Return(catalogMeal interfaces.CatalogMeal, err error) *CatalogService_CreateGeneratedMeal_Call {
	_c.Call.Return(catalogMeal, err)
	return _c
}

func (_c *CatalogService_CreateGeneratedMeal_Call) RunAndReturn(run func(ctx context.Context, input interfaces.GeneratedCatalogMealInput) (interfaces.CatalogMeal, error)) *CatalogService_CreateGeneratedMeal_Call {
	_c.Call.Return(run)
	return _c
}

// GetMeal provides a mock function for the type CatalogService
func (_mock *CatalogService) GetMeal(ctx context.Context, id uuid.UUID) (interfaces.CatalogMeal, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMeal")
	}

	var r0 interfaces.CatalogMeal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (interfaces.CatalogMeal, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) interfaces.CatalogMeal); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(interfaces.CatalogMeal)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CatalogService_GetMeal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMeal'
type CatalogService_GetMeal_Call struct {
	*mock.Call
}

// GetMeal is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *CatalogService_Expecter) GetMeal(ctx interface{}, id interface{}) *CatalogService_GetMeal_Call {
	return &CatalogService_GetMeal_Call{Call: _e.mock.On("GetMeal", ctx, id)}
}

func (_c *CatalogService_GetMeal_Call) Run(run func(ctx context.Context, id uuid.UUID)) *CatalogService_GetMeal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CatalogService_GetMeal_Call) Return(catalogMeal interfaces.CatalogMeal, err error) *CatalogService_GetMeal_Call {
	_c.Call.Return(catalogMeal, err)
	return _c
}

func (_c *CatalogService_GetMeal_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (interfaces.CatalogMeal, error)) *CatalogService_GetMeal_Call {
	_c.Call.Return(run)
	return _c
}

// ListCategories provides a mock function for the type CatalogService
func (_mock *CatalogService) ListCategories(ctx context.Context) ([]interfaces.CatalogCategory, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListCategories")
	}

	var r0 []interfaces.CatalogCategory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]interfaces.CatalogCategory, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []interfaces.CatalogCategory); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interfaces.CatalogCategory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CatalogService_ListCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCategories'
type CatalogService_ListCategories_Call struct {
	*mock.Call
}

// ListCategories is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CatalogService_Expecter) ListCategories(ctx interface{}) *CatalogService_ListCategories_Call {
	return &CatalogService_ListCategories_Call{Call: _e.mock.On("ListCategories", ctx)}
}

func (_c *CatalogService_ListCategories_Call) Run(run func(ctx context.Context)) *CatalogService_ListCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CatalogService_ListCategories_Call) Return(catalogCategorys []interfaces.CatalogCategory, err error) *CatalogService_ListCategories_Call {
	_c.Call.Return(catalogCategorys, err)
	return _c
}

func (_c *CatalogService_ListCategories_Call) RunAndReturn(run func(ctx context.Context) ([]interfaces.CatalogCategory, error)) *CatalogService_ListCategories_Call {
	_c.Call.Return(run)
	return _c
}

// SearchMeals provides a mock function for the type CatalogService
func (_mock *CatalogService) SearchMeals(ctx context.Context, query interfaces.CatalogQuery) (interfaces.CatalogMealPage, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for SearchMeals")
	}

	var r0 interfaces.CatalogMealPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.CatalogQuery) (interfaces.CatalogMealPage, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.CatalogQuery) interfaces.CatalogMealPage); ok {
		r0 = returnFunc(ctx, query)
	} else {
		r0 = ret.Get(0).(interfaces.CatalogMealPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interfaces.CatalogQuery) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CatalogService_SearchMeals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchMeals'
type CatalogService_SearchMeals_Call struct {
	*mock.Call
}

// SearchMeals is a helper method to define mock.On call
//   - ctx context.Context
//   - query interfaces.CatalogQuery
func (_e *CatalogService_Expecter) SearchMeals(ctx interface{}, query interface{}) *CatalogService_SearchMeals_Call {
	return &CatalogService_SearchMeals_Call{Call: _e.mock.On("SearchMeals", ctx, query)}
}

func (_c *CatalogService_SearchMeals_Call) Run(run func(ctx context.Context, query interfaces.CatalogQuery)) *CatalogService_SearchMeals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interfaces.CatalogQuery
		if args[1] != nil {
			arg1 = args[1].(interfaces.CatalogQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CatalogService_SearchMeals_Call) Return(catalogMealPage interfaces.CatalogMealPage, err error) *CatalogService_SearchMeals_Call {
	_c.Call.Return(catalogMealPage, err)
	return _c
}

func (_c *CatalogService_SearchMeals_Call) RunAndReturn(run func(ctx context.Context, query interfaces.CatalogQuery) (interfaces.CatalogMealPage, error)) *CatalogService_SearchMeals_Call {
	_c.Call.Return(run)
	return _c
}
