// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"fyp/food-rs/types/model"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewCustomMealRepository creates a new instance of CustomMealRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomMealRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomMealRepository {
	mock := &CustomMealRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CustomMealRepository is an autogenerated mock type for the CustomMealRepository type
type CustomMealRepository struct {
	mock.Mock
}

type CustomMealRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CustomMealRepository) EXPECT() *CustomMealRepository_Expecter {
	return &CustomMealRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type CustomMealRepository
func (_mock *CustomMealRepository) Create(ctx context.Context, meal *model.CustomMealItem) (*model.CustomMealItem, error) {
	ret := _mock.Called(ctx, meal)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.CustomMealItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.CustomMealItem) (*model.CustomMealItem, error)); ok {
		return returnFunc(ctx, meal)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.CustomMealItem) *model.CustomMealItem); ok {
		r0 = returnFunc(ctx, meal)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CustomMealItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.CustomMealItem) error); ok {
		r1 = returnFunc(ctx, meal)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CustomMealRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CustomMealRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - meal *model.CustomMealItem
func (_e *CustomMealRepository_Expecter) Create(ctx interface{}, meal interface{}) *CustomMealRepository_Create_Call {
	return &CustomMealRepository_Create_Call{Call: _e.mock.On("Create", ctx, meal)}
}

func (_c *CustomMealRepository_Create_Call) Run(run func(ctx context.Context, meal *model.CustomMealItem)) *CustomMealRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.CustomMealItem
		if args[1] != nil {
			arg1 = args[1].(*model.CustomMealItem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CustomMealRepository_Create_Call) Return(customMealItem *model.CustomMealItem, err error) *CustomMealRepository_Create_Call {
	_c.Call.Return(customMealItem, err)
	return _c
}

func (_c *CustomMealRepository_Create_Call) RunAndReturn(run func(ctx context.Context, meal *model.CustomMealItem) (*model.CustomMealItem, error)) *CustomMealRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindVisibleByID provides a mock function for the type CustomMealRepository
func (_mock *CustomMealRepository) FindVisibleByID(ctx context.Context, userID uuid.UUID, customMealID uuid.UUID) (*model.CustomMealItem, error) {
	ret := _mock.Called(ctx, userID, customMealID)

	if len(ret) == 0 {
		panic("no return value specified for FindVisibleByID")
	}

	var r0 *model.CustomMealItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.CustomMealItem, error)); ok {
		return returnFunc(ctx, userID, customMealID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.CustomMealItem); ok {
		r0 = returnFunc(ctx, userID, customMealID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CustomMealItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, customMealID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CustomMealRepository_FindVisibleByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindVisibleByID'
type CustomMealRepository_FindVisibleByID_Call struct {
	*mock.Call
}

// FindVisibleByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - customMealID uuid.UUID
func (_e *CustomMealRepository_Expecter) FindVisibleByID(ctx interface{}, userID interface{}, customMealID interface{}) *CustomMealRepository_FindVisibleByID_Call {
	return &CustomMealRepository_FindVisibleByID_Call{Call: _e.mock.On("FindVisibleByID", ctx, userID, customMealID)}
}

func (_c *CustomMealRepository_FindVisibleByID_Call) Run(run func(ctx context.Context, userID uuid.UUID, customMealID uuid.UUID)) *CustomMealRepository_FindVisibleByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CustomMealRepository_FindVisibleByID_Call) Return(customMealItem *model.CustomMealItem, err error) *CustomMealRepository_FindVisibleByID_Call {
	_c.Call.Return(customMealItem, err)
	return _c
}

func (_c *CustomMealRepository_FindVisibleByID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, customMealID uuid.UUID) (*model.CustomMealItem, error)) *CustomMealRepository_FindVisibleByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListOwnedByUser provides a mock function for the type CustomMealRepository
func (_mock *CustomMealRepository) ListOwnedByUser(ctx context.Context, userID uuid.UUID, query string) ([]model.CustomMealItem, error) {
	ret := _mock.Called(ctx, userID, query)

	if len(ret) == 0 {
		panic("no return value specified for ListOwnedByUser")
	}

	var r0 []model.CustomMealItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]model.CustomMealItem, error)); ok {
		return returnFunc(ctx, userID, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []model.CustomMealItem); ok {
		r0 = returnFunc(ctx, userID, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CustomMealItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, userID, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CustomMealRepository_ListOwnedByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOwnedByUser'
type CustomMealRepository_ListOwnedByUser_Call struct {
	*mock.Call
}

// ListOwnedByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - query string
func (_e *CustomMealRepository_Expecter) ListOwnedByUser(ctx interface{}, userID interface{}, query interface{}) *CustomMealRepository_ListOwnedByUser_Call {
	return &CustomMealRepository_ListOwnedByUser_Call{Call: _e.mock.On("ListOwnedByUser", ctx, userID, query)}
}

func (_c *CustomMealRepository_ListOwnedByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID, query string)) *CustomMealRepository_ListOwnedByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CustomMealRepository_ListOwnedByUser_Call) Return(customMealItems []model.CustomMealItem, err error) *CustomMealRepository_ListOwnedByUser_Call {
	_c.Call.Return(customMealItems, err)
	return _c
}

func (_c *CustomMealRepository_ListOwnedByUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, query string) ([]model.CustomMealItem, error)) *CustomMealRepository_ListOwnedByUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListSharedFromOtherUsers provides a mock function for the type CustomMealRepository
func (_mock *CustomMealRepository) ListSharedFromOtherUsers(ctx context.Context, userID uuid.UUID, query string) ([]model.CustomMealItem, error) {
	ret := _mock.Called(ctx, userID, query)

	if len(ret) == 0 {
		panic("no return value specified for ListSharedFromOtherUsers")
	}

	var r0 []model.CustomMealItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]model.CustomMealItem, error)); ok {
		return returnFunc(ctx, userID, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []model.CustomMealItem); ok {
		r0 = returnFunc(ctx, userID, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CustomMealItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, userID, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CustomMealRepository_ListSharedFromOtherUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSharedFromOtherUsers'
type CustomMealRepository_ListSharedFromOtherUsers_Call struct {
	*mock.Call
}

// ListSharedFromOtherUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - query string
func (_e *CustomMealRepository_Expecter) ListSharedFromOtherUsers(ctx interface{}, userID interface{}, query interface{}) *CustomMealRepository_ListSharedFromOtherUsers_Call {
	return &CustomMealRepository_ListSharedFromOtherUsers_Call{Call: _e.mock.On("ListSharedFromOtherUsers", ctx, userID, query)}
}

func (_c *CustomMealRepository_ListSharedFromOtherUsers_Call) Run(run func(ctx context.Context, userID uuid.UUID, query string)) *CustomMealRepository_ListSharedFromOtherUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CustomMealRepository_ListSharedFromOtherUsers_Call) Return(customMealItems []model.CustomMealItem, err error) *CustomMealRepository_ListSharedFromOtherUsers_Call {
	_c.Call.Return(customMealItems, err)
	return _c
}

func (_c *CustomMealRepository_ListSharedFromOtherUsers_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, query string) ([]model.CustomMealItem, error)) *CustomMealRepository_ListSharedFromOtherUsers_Call {
	_c.Call.Return(run)
	return _c
}
