// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"fyp/food-rs/internal/interfaces"

	mock "github.com/stretchr/testify/mock"
)

// NewCustomMealAutocompleter creates a new instance of CustomMealAutocompleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomMealAutocompleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomMealAutocompleter {
	mock := &CustomMealAutocompleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CustomMealAutocompleter is an autogenerated mock type for the CustomMealAutocompleter type
type CustomMealAutocompleter struct {
	mock.Mock
}

type CustomMealAutocompleter_Expecter struct {
	mock *mock.Mock
}

func (_m *CustomMealAutocompleter) EXPECT() *CustomMealAutocompleter_Expecter {
	return &CustomMealAutocompleter_Expecter{mock: &_m.Mock}
}

// AutocompleteCustomMeal provides a mock function for the type CustomMealAutocompleter
func (_mock *CustomMealAutocompleter) AutocompleteCustomMeal(ctx context.Context, input interfaces.CustomMealAutocompleteInput) (interfaces.CustomMealAutocompleteResponse, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for AutocompleteCustomMeal")
	}

	var r0 interfaces.CustomMealAutocompleteResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.CustomMealAutocompleteInput) (interfaces.CustomMealAutocompleteResponse, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.CustomMealAutocompleteInput) interfaces.CustomMealAutocompleteResponse); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(interfaces.CustomMealAutocompleteResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interfaces.CustomMealAutocompleteInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CustomMealAutocompleter_AutocompleteCustomMeal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AutocompleteCustomMeal'
type CustomMealAutocompleter_AutocompleteCustomMeal_Call struct {
	*mock.Call
}

// AutocompleteCustomMeal is a helper method to define mock.On call
//   - ctx context.Context
//   - input interfaces.CustomMealAutocompleteInput
func (_e *CustomMealAutocompleter_Expecter) AutocompleteCustomMeal(ctx interface{}, input interface{}) *CustomMealAutocompleter_AutocompleteCustomMeal_Call {
	return &CustomMealAutocompleter_AutocompleteCustomMeal_Call{Call: _e.mock.On("AutocompleteCustomMeal", ctx, input)}
}

func (_c *CustomMealAutocompleter_AutocompleteCustomMeal_Call) Run(run func(ctx context.Context, input interfaces.CustomMealAutocompleteInput)) *CustomMealAutocompleter_AutocompleteCustomMeal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interfaces.CustomMealAutocompleteInput
		if args[1] != nil {
			arg1 = args[1].(interfaces.CustomMealAutocompleteInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CustomMealAutocompleter_AutocompleteCustomMeal_Call) Return(customMealAutocompleteResponse interfaces.CustomMealAutocompleteResponse, err error) *CustomMealAutocompleter_AutocompleteCustomMeal_Call {
	_c.Call.Return(customMealAutocompleteResponse, err)
	return _c
}

func (_c *CustomMealAutocompleter_AutocompleteCustomMeal_Call) RunAndReturn(run func(ctx context.Context, input interfaces.CustomMealAutocompleteInput) (interfaces.CustomMealAutocompleteResponse, error)) *CustomMealAutocompleter_AutocompleteCustomMeal_Call {
	_c.Call.Return(run)
	return _c
}
