// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"fyp/food-rs/internal/interfaces"

	mock "github.com/stretchr/testify/mock"
)

// NewFoodSearcher creates a new instance of FoodSearcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFoodSearcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *FoodSearcher {
	mock := &FoodSearcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FoodSearcher is an autogenerated mock type for the FoodSearcher type
type FoodSearcher struct {
	mock.Mock
}

type FoodSearcher_Expecter struct {
	mock *mock.Mock
}

func (_m *FoodSearcher) EXPECT() *FoodSearcher_Expecter {
	return &FoodSearcher_Expecter{mock: &_m.Mock}
}

// SearchFood provides a mock function for the type FoodSearcher
func (_mock *FoodSearcher) SearchFood(ctx context.Context, query string) (interfaces.FoodSearchResult, bool, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for SearchFood")
	}

	var r0 interfaces.FoodSearchResult
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (interfaces.FoodSearchResult, bool, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) interfaces.FoodSearchResult); ok {
		r0 = returnFunc(ctx, query)
	} else {
		r0 = ret.Get(0).(interfaces.FoodSearchResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, query)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// FoodSearcher_SearchFood_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchFood'
type FoodSearcher_SearchFood_Call struct {
	*mock.Call
}

// SearchFood is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *FoodSearcher_Expecter) SearchFood(ctx interface{}, query interface{}) *FoodSearcher_SearchFood_Call {
	return &FoodSearcher_SearchFood_Call{Call: _e.mock.On("SearchFood", ctx, query)}
}

func (_c *FoodSearcher_SearchFood_Call) Run(run func(ctx context.Context, query string)) *FoodSearcher_SearchFood_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FoodSearcher_SearchFood_Call) Return(foodSearchResult interfaces.FoodSearchResult, b bool, err error) *FoodSearcher_SearchFood_Call {
	_c.Call.Return(foodSearchResult, b, err)
	return _c
}

func (_c *FoodSearcher_SearchFood_Call) RunAndReturn(run func(ctx context.Context, query string) (interfaces.FoodSearchResult, bool, error)) *FoodSearcher_SearchFood_Call {
	_c.Call.Return(run)
	return _c
}
