// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"fyp/food-rs/internal/interfaces"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewFoodCandidateSearcher creates a new instance of FoodCandidateSearcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFoodCandidateSearcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *FoodCandidateSearcher {
	mock := &FoodCandidateSearcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FoodCandidateSearcher is an autogenerated mock type for the FoodCandidateSearcher type
type FoodCandidateSearcher struct {
	mock.Mock
}

type FoodCandidateSearcher_Expecter struct {
	mock *mock.Mock
}

func (_m *FoodCandidateSearcher) EXPECT() *FoodCandidateSearcher_Expecter {
	return &FoodCandidateSearcher_Expecter{mock: &_m.Mock}
}

// SearchFoodCandidates provides a mock function for the type FoodCandidateSearcher
func (_mock *FoodCandidateSearcher) SearchFoodCandidates(ctx context.Context, userID uuid.UUID, queries []string, limit int) ([]interfaces.FoodMatchCandidate, error) {
	ret := _mock.Called(ctx, userID, queries, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchFoodCandidates")
	}

	var r0 []interfaces.FoodMatchCandidate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []string, int) ([]interfaces.FoodMatchCandidate, error)); ok {
		return returnFunc(ctx, userID, queries, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []string, int) []interfaces.FoodMatchCandidate); ok {
		r0 = returnFunc(ctx, userID, queries, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interfaces.FoodMatchCandidate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, []string, int) error); ok {
		r1 = returnFunc(ctx, userID, queries, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FoodCandidateSearcher_SearchFoodCandidates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchFoodCandidates'
type FoodCandidateSearcher_SearchFoodCandidates_Call struct {
	*mock.Call
}

// SearchFoodCandidates is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - queries []string
//   - limit int
func (_e *FoodCandidateSearcher_Expecter) SearchFoodCandidates(ctx interface{}, userID interface{}, queries interface{}, limit interface{}) *FoodCandidateSearcher_SearchFoodCandidates_Call {
	return &FoodCandidateSearcher_SearchFoodCandidates_Call{Call: _e.mock.On("SearchFoodCandidates", ctx, userID, queries, limit)}
}

func (_c *FoodCandidateSearcher_SearchFoodCandidates_Call) Run(run func(ctx context.Context, userID uuid.UUID, queries []string, limit int)) *FoodCandidateSearcher_SearchFoodCandidates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *FoodCandidateSearcher_SearchFoodCandidates_Call) Return(foodMatchCandidates []interfaces.FoodMatchCandidate, err error) *FoodCandidateSearcher_SearchFoodCandidates_Call {
	_c.Call.Return(foodMatchCandidates, err)
	return _c
}

func (_c *FoodCandidateSearcher_SearchFoodCandidates_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, queries []string, limit int) ([]interfaces.FoodMatchCandidate, error)) *FoodCandidateSearcher_SearchFoodCandidates_Call {
	_c.Call.Return(run)
	return _c
}
