// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"fyp/food-rs/internal/interfaces"

	mock "github.com/stretchr/testify/mock"
)

// NewMealGenerator creates a new instance of MealGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMealGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MealGenerator {
	mock := &MealGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MealGenerator is an autogenerated mock type for the MealGenerator type
type MealGenerator struct {
	mock.Mock
}

type MealGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MealGenerator) EXPECT() *MealGenerator_Expecter {
	return &MealGenerator_Expecter{mock: &_m.Mock}
}

// GenerateMeals provides a mock function for the type MealGenerator
func (_mock *MealGenerator) GenerateMeals(ctx context.Context, input interfaces.MealPromptInput) (interfaces.GeminiMealsResponse, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GenerateMeals")
	}

	var r0 interfaces.GeminiMealsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.MealPromptInput) (interfaces.GeminiMealsResponse, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interfaces.MealPromptInput) interfaces.GeminiMealsResponse); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(interfaces.GeminiMealsResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interfaces.MealPromptInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MealGenerator_GenerateMeals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateMeals'
type MealGenerator_GenerateMeals_Call struct {
	*mock.Call
}

// GenerateMeals is a helper method to define mock.On call
//   - ctx context.Context
//   - input interfaces.MealPromptInput
func (_e *MealGenerator_Expecter) GenerateMeals(ctx interface{}, input interface{}) *MealGenerator_GenerateMeals_Call {
	return &MealGenerator_GenerateMeals_Call{Call: _e.mock.On("GenerateMeals", ctx, input)}
}

func (_c *MealGenerator_GenerateMeals_Call) Run(run func(ctx context.Context, input interfaces.MealPromptInput)) *MealGenerator_GenerateMeals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interfaces.MealPromptInput
		if args[1] != nil {
			arg1 = args[1].(interfaces.MealPromptInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MealGenerator_GenerateMeals_Call) Return(geminiMealsResponse interfaces.GeminiMealsResponse, err error) *MealGenerator_GenerateMeals_Call {
	_c.Call.Return(geminiMealsResponse, err)
	return _c
}

func (_c *MealGenerator_GenerateMeals_Call) RunAndReturn(run func(ctx context.Context, input interfaces.MealPromptInput) (interfaces.GeminiMealsResponse, error)) *MealGenerator_GenerateMeals_Call {
	_c.Call.Return(run)
	return _c
}
