// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"fyp/food-rs/internal/interfaces"

	mock "github.com/stretchr/testify/mock"
)

// NewMealMatchAdjudicator creates a new instance of MealMatchAdjudicator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMealMatchAdjudicator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MealMatchAdjudicator {
	mock := &MealMatchAdjudicator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MealMatchAdjudicator is an autogenerated mock type for the MealMatchAdjudicator type
type MealMatchAdjudicator struct {
	mock.Mock
}

type MealMatchAdjudicator_Expecter struct {
	mock *mock.Mock
}

func (_m *MealMatchAdjudicator) EXPECT() *MealMatchAdjudicator_Expecter {
	return &MealMatchAdjudicator_Expecter{mock: &_m.Mock}
}

// ResolveMatches provides a mock function for the type MealMatchAdjudicator
func (_mock *MealMatchAdjudicator) ResolveMatches(ctx context.Context, tasks []interfaces.MealMatchTask) ([]interfaces.MealMatchDecision, error) {
	ret := _mock.Called(ctx, tasks)

	if len(ret) == 0 {
		panic("no return value specified for ResolveMatches")
	}

	var r0 []interfaces.MealMatchDecision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []interfaces.MealMatchTask) ([]interfaces.MealMatchDecision, error)); ok {
		return returnFunc(ctx, tasks)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []interfaces.MealMatchTask) []interfaces.MealMatchDecision); ok {
		r0 = returnFunc(ctx, tasks)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interfaces.MealMatchDecision)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []interfaces.MealMatchTask) error); ok {
		r1 = returnFunc(ctx, tasks)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MealMatchAdjudicator_ResolveMatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveMatches'
type MealMatchAdjudicator_ResolveMatches_Call struct {
	*mock.Call
}

// ResolveMatches is a helper method to define mock.On call
//   - ctx context.Context
//   - tasks []interfaces.MealMatchTask
func (_e *MealMatchAdjudicator_Expecter) ResolveMatches(ctx interface{}, tasks interface{}) *MealMatchAdjudicator_ResolveMatches_Call {
	return &MealMatchAdjudicator_ResolveMatches_Call{Call: _e.mock.On("ResolveMatches", ctx, tasks)}
}

func (_c *MealMatchAdjudicator_ResolveMatches_Call) Run(run func(ctx context.Context, tasks []interfaces.MealMatchTask)) *MealMatchAdjudicator_ResolveMatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []interfaces.MealMatchTask
		if args[1] != nil {
			arg1 = args[1].([]interfaces.MealMatchTask)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MealMatchAdjudicator_ResolveMatches_Call) Return(mealMatchDecisions []interfaces.MealMatchDecision, err error) *MealMatchAdjudicator_ResolveMatches_Call {
	_c.Call.Return(mealMatchDecisions, err)
	return _c
}

func (_c *MealMatchAdjudicator_ResolveMatches_Call) RunAndReturn(run func(ctx context.Context, tasks []interfaces.MealMatchTask) ([]interfaces.MealMatchDecision, error)) *MealMatchAdjudicator_ResolveMatches_Call {
	_c.Call.Return(run)
	return _c
}
