// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"fyp/food-rs/types/model"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewPreferenceRepository creates a new instance of PreferenceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPreferenceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PreferenceRepository {
	mock := &PreferenceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PreferenceRepository is an autogenerated mock type for the PreferenceRepository type
type PreferenceRepository struct {
	mock.Mock
}

type PreferenceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PreferenceRepository) EXPECT() *PreferenceRepository_Expecter {
	return &PreferenceRepository_Expecter{mock: &_m.Mock}
}

// FindByUserID provides a mock function for the type PreferenceRepository
func (_mock *PreferenceRepository) FindByUserID(ctx context.Context, userID uuid.UUID) (*model.UserPreference, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 *model.UserPreference
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.UserPreference, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.UserPreference); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserPreference)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PreferenceRepository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type PreferenceRepository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *PreferenceRepository_Expecter) FindByUserID(ctx interface{}, userID interface{}) *PreferenceRepository_FindByUserID_Call {
	return &PreferenceRepository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *PreferenceRepository_FindByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *PreferenceRepository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PreferenceRepository_FindByUserID_Call) Return(userPreference *model.UserPreference, err error) *PreferenceRepository_FindByUserID_Call {
	_c.Call.Return(userPreference, err)
	return _c
}

func (_c *PreferenceRepository_FindByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (*model.UserPreference, error)) *PreferenceRepository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataSharingConsent provides a mock function for the type PreferenceRepository
func (_mock *PreferenceRepository) UpdateDataSharingConsent(ctx context.Context, userID uuid.UUID, consent bool) error {
	ret := _mock.Called(ctx, userID, consent)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataSharingConsent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) error); ok {
		r0 = returnFunc(ctx, userID, consent)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PreferenceRepository_UpdateDataSharingConsent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataSharingConsent'
type PreferenceRepository_UpdateDataSharingConsent_Call struct {
	*mock.Call
}

// UpdateDataSharingConsent is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - consent bool
func (_e *PreferenceRepository_Expecter) UpdateDataSharingConsent(ctx interface{}, userID interface{}, consent interface{}) *PreferenceRepository_UpdateDataSharingConsent_Call {
	return &PreferenceRepository_UpdateDataSharingConsent_Call{Call: _e.mock.On("UpdateDataSharingConsent", ctx, userID, consent)}
}

func (_c *PreferenceRepository_UpdateDataSharingConsent_Call) Run(run func(ctx context.Context, userID uuid.UUID, consent bool)) *PreferenceRepository_UpdateDataSharingConsent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PreferenceRepository_UpdateDataSharingConsent_Call) Return(err error) *PreferenceRepository_UpdateDataSharingConsent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PreferenceRepository_UpdateDataSharingConsent_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, consent bool) error) *PreferenceRepository_UpdateDataSharingConsent_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type PreferenceRepository
func (_mock *PreferenceRepository) Upsert(ctx context.Context, preference *model.UserPreference) (*model.UserPreference, error) {
	ret := _mock.Called(ctx, preference)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 *model.UserPreference
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.UserPreference) (*model.UserPreference, error)); ok {
		return returnFunc(ctx, preference)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.UserPreference) *model.UserPreference); ok {
		r0 = returnFunc(ctx, preference)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserPreference)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.UserPreference) error); ok {
		r1 = returnFunc(ctx, preference)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PreferenceRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type PreferenceRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - preference *model.UserPreference
func (_e *PreferenceRepository_Expecter) Upsert(ctx interface{}, preference interface{}) *PreferenceRepository_Upsert_Call {
	return &PreferenceRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, preference)}
}

func (_c *PreferenceRepository_Upsert_Call) Run(run func(ctx context.Context, preference *model.UserPreference)) *PreferenceRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.UserPreference
		if args[1] != nil {
			arg1 = args[1].(*model.UserPreference)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PreferenceRepository_Upsert_Call) Return(userPreference *model.UserPreference, err error) *PreferenceRepository_Upsert_Call {
	_c.Call.Return(userPreference, err)
	return _c
}

func (_c *PreferenceRepository_Upsert_Call) RunAndReturn(run func(ctx context.Context, preference *model.UserPreference) (*model.UserPreference, error)) *PreferenceRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
