// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"fyp/food-rs/internal/interfaces"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewPreferenceService creates a new instance of PreferenceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPreferenceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PreferenceService {
	mock := &PreferenceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PreferenceService is an autogenerated mock type for the PreferenceService type
type PreferenceService struct {
	mock.Mock
}

type PreferenceService_Expecter struct {
	mock *mock.Mock
}

func (_m *PreferenceService) EXPECT() *PreferenceService_Expecter {
	return &PreferenceService_Expecter{mock: &_m.Mock}
}

// CompleteOnboarding provides a mock function for the type PreferenceService
func (_mock *PreferenceService) CompleteOnboarding(ctx context.Context, userID uuid.UUID, input interfaces.PreferenceInput) (*interfaces.PreferenceResponse, error) {
	ret := _mock.Called(ctx, userID, input)

	if len(ret) == 0 {
		panic("no return value specified for CompleteOnboarding")
	}

	var r0 *interfaces.PreferenceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, interfaces.PreferenceInput) (*interfaces.PreferenceResponse, error)); ok {
		return returnFunc(ctx, userID, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, interfaces.PreferenceInput) *interfaces.PreferenceResponse); ok {
		r0 = returnFunc(ctx, userID, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.PreferenceResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, interfaces.PreferenceInput) error); ok {
		r1 = returnFunc(ctx, userID, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PreferenceService_CompleteOnboarding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteOnboarding'
type PreferenceService_CompleteOnboarding_Call struct {
	*mock.Call
}

// CompleteOnboarding is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - input interfaces.PreferenceInput
func (_e *PreferenceService_Expecter) CompleteOnboarding(ctx interface{}, userID interface{}, input interface{}) *PreferenceService_CompleteOnboarding_Call {
	return &PreferenceService_CompleteOnboarding_Call{Call: _e.mock.On("CompleteOnboarding", ctx, userID, input)}
}

func (_c *PreferenceService_CompleteOnboarding_Call) Run(run func(ctx context.Context, userID uuid.UUID, input interfaces.PreferenceInput)) *PreferenceService_CompleteOnboarding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 interfaces.PreferenceInput
		if args[2] != nil {
			arg2 = args[2].(interfaces.PreferenceInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PreferenceService_CompleteOnboarding_Call) Return(preferenceResponse *interfaces.PreferenceResponse, err error) *PreferenceService_CompleteOnboarding_Call {
	_c.Call.Return(preferenceResponse, err)
	return _c
}

func (_c *PreferenceService_CompleteOnboarding_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, input interfaces.PreferenceInput) (*interfaces.PreferenceResponse, error)) *PreferenceService_CompleteOnboarding_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function for the type PreferenceService
func (_mock *PreferenceService) GetByUserID(ctx context.Context, userID uuid.UUID) (*interfaces.PreferenceResponse, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 *interfaces.PreferenceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*interfaces.PreferenceResponse, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *interfaces.PreferenceResponse); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.PreferenceResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PreferenceService_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type PreferenceService_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *PreferenceService_Expecter) GetByUserID(ctx interface{}, userID interface{}) *PreferenceService_GetByUserID_Call {
	return &PreferenceService_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *PreferenceService_GetByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *PreferenceService_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PreferenceService_GetByUserID_Call) Return(preferenceResponse *interfaces.PreferenceResponse, err error) *PreferenceService_GetByUserID_Call {
	_c.Call.Return(preferenceResponse, err)
	return _c
}

func (_c *PreferenceService_GetByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (*interfaces.PreferenceResponse, error)) *PreferenceService_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type PreferenceService
func (_mock *PreferenceService) Update(ctx context.Context, userID uuid.UUID, input interfaces.PreferenceInput) (*interfaces.PreferenceResponse, error) {
	ret := _mock.Called(ctx, userID, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *interfaces.PreferenceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, interfaces.PreferenceInput) (*interfaces.PreferenceResponse, error)); ok {
		return returnFunc(ctx, userID, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, interfaces.PreferenceInput) *interfaces.PreferenceResponse); ok {
		r0 = returnFunc(ctx, userID, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.PreferenceResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, interfaces.PreferenceInput) error); ok {
		r1 = returnFunc(ctx, userID, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PreferenceService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type PreferenceService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - input interfaces.PreferenceInput
func (_e *PreferenceService_Expecter) Update(ctx interface{}, userID interface{}, input interface{}) *PreferenceService_Update_Call {
	return &PreferenceService_Update_Call{Call: _e.mock.On("Update", ctx, userID, input)}
}

func (_c *PreferenceService_Update_Call) Run(run func(ctx context.Context, userID uuid.UUID, input interfaces.PreferenceInput)) *PreferenceService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 interfaces.PreferenceInput
		if args[2] != nil {
			arg2 = args[2].(interfaces.PreferenceInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PreferenceService_Update_Call) Return(preferenceResponse *interfaces.PreferenceResponse, err error) *PreferenceService_Update_Call {
	_c.Call.Return(preferenceResponse, err)
	return _c
}

func (_c *PreferenceService_Update_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, input interfaces.PreferenceInput) (*interfaces.PreferenceResponse, error)) *PreferenceService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataSharingConsent provides a mock function for the type PreferenceService
func (_mock *PreferenceService) UpdateDataSharingConsent(ctx context.Context, userID uuid.UUID, consent bool) error {
	ret := _mock.Called(ctx, userID, consent)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataSharingConsent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) error); ok {
		r0 = returnFunc(ctx, userID, consent)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PreferenceService_UpdateDataSharingConsent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataSharingConsent'
type PreferenceService_UpdateDataSharingConsent_Call struct {
	*mock.Call
}

// UpdateDataSharingConsent is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - consent bool
func (_e *PreferenceService_Expecter) UpdateDataSharingConsent(ctx interface{}, userID interface{}, consent interface{}) *PreferenceService_UpdateDataSharingConsent_Call {
	return &PreferenceService_UpdateDataSharingConsent_Call{Call: _e.mock.On("UpdateDataSharingConsent", ctx, userID, consent)}
}

func (_c *PreferenceService_UpdateDataSharingConsent_Call) Run(run func(ctx context.Context, userID uuid.UUID, consent bool)) *PreferenceService_UpdateDataSharingConsent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PreferenceService_UpdateDataSharingConsent_Call) Return(err error) *PreferenceService_UpdateDataSharingConsent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PreferenceService_UpdateDataSharingConsent_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, consent bool) error) *PreferenceService_UpdateDataSharingConsent_Call {
	_c.Call.Return(run)
	return _c
}
