// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"fyp/food-rs/internal/interfaces"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewRecommendationService creates a new instance of RecommendationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRecommendationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *RecommendationService {
	mock := &RecommendationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RecommendationService is an autogenerated mock type for the RecommendationService type
type RecommendationService struct {
	mock.Mock
}

type RecommendationService_Expecter struct {
	mock *mock.Mock
}

func (_m *RecommendationService) EXPECT() *RecommendationService_Expecter {
	return &RecommendationService_Expecter{mock: &_m.Mock}
}

// GenerateRecommendationResult provides a mock function for the type RecommendationService
func (_mock *RecommendationService) GenerateRecommendationResult(ctx context.Context, userID uuid.UUID, input interfaces.MealPromptInput) (interfaces.RecommendationResult, error) {
	ret := _mock.Called(ctx, userID, input)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRecommendationResult")
	}

	var r0 interfaces.RecommendationResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, interfaces.MealPromptInput) (interfaces.RecommendationResult, error)); ok {
		return returnFunc(ctx, userID, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, interfaces.MealPromptInput) interfaces.RecommendationResult); ok {
		r0 = returnFunc(ctx, userID, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.RecommendationResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, interfaces.MealPromptInput) error); ok {
		r1 = returnFunc(ctx, userID, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RecommendationService_GenerateRecommendationResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRecommendationResult'
type RecommendationService_GenerateRecommendationResult_Call struct {
	*mock.Call
}

// GenerateRecommendationResult is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - input interfaces.MealPromptInput
func (_e *RecommendationService_Expecter) GenerateRecommendationResult(ctx interface{}, userID interface{}, input interface{}) *RecommendationService_GenerateRecommendationResult_Call {
	return &RecommendationService_GenerateRecommendationResult_Call{Call: _e.mock.On("GenerateRecommendationResult", ctx, userID, input)}
}

func (_c *RecommendationService_GenerateRecommendationResult_Call) Run(run func(ctx context.Context, userID uuid.UUID, input interfaces.MealPromptInput)) *RecommendationService_GenerateRecommendationResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 interfaces.MealPromptInput
		if args[2] != nil {
			arg2 = args[2].(interfaces.MealPromptInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RecommendationService_GenerateRecommendationResult_Call) Return(recommendationResult interfaces.RecommendationResult, err error) *RecommendationService_GenerateRecommendationResult_Call {
	_c.Call.Return(recommendationResult, err)
	return _c
}

func (_c *RecommendationService_GenerateRecommendationResult_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, input interfaces.MealPromptInput) (interfaces.RecommendationResult, error)) *RecommendationService_GenerateRecommendationResult_Call {
	_c.Call.Return(run)
	return _c
}
