// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"fyp/food-rs/types/model"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewRefreshTokenRepository creates a new instance of RefreshTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshTokenRepository {
	mock := &RefreshTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RefreshTokenRepository is an autogenerated mock type for the RefreshTokenRepository type
type RefreshTokenRepository struct {
	mock.Mock
}

type RefreshTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *RefreshTokenRepository) EXPECT() *RefreshTokenRepository_Expecter {
	return &RefreshTokenRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type RefreshTokenRepository
func (_mock *RefreshTokenRepository) Create(ctx context.Context, refreshToken *model.RefreshToken) error {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.RefreshToken) error); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RefreshTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type RefreshTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken *model.RefreshToken
func (_e *RefreshTokenRepository_Expecter) Create(ctx interface{}, refreshToken interface{}) *RefreshTokenRepository_Create_Call {
	return &RefreshTokenRepository_Create_Call{Call: _e.mock.On("Create", ctx, refreshToken)}
}

func (_c *RefreshTokenRepository_Create_Call) Run(run func(ctx context.Context, refreshToken *model.RefreshToken)) *RefreshTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.RefreshToken
		if args[1] != nil {
			arg1 = args[1].(*model.RefreshToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RefreshTokenRepository_Create_Call) Return(err error) *RefreshTokenRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RefreshTokenRepository_Create_Call) RunAndReturn(run func(ctx context.Context, refreshToken *model.RefreshToken) error) *RefreshTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByHash provides a mock function for the type RefreshTokenRepository
func (_mock *RefreshTokenRepository) FindByHash(ctx context.Context, hash string) (*model.RefreshToken, error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for FindByHash")
	}

	var r0 *model.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.RefreshToken, error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.RefreshToken); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RefreshToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RefreshTokenRepository_FindByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByHash'
type RefreshTokenRepository_FindByHash_Call struct {
	*mock.Call
}

// FindByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *RefreshTokenRepository_Expecter) FindByHash(ctx interface{}, hash interface{}) *RefreshTokenRepository_FindByHash_Call {
	return &RefreshTokenRepository_FindByHash_Call{Call: _e.mock.On("FindByHash", ctx, hash)}
}

func (_c *RefreshTokenRepository_FindByHash_Call) Run(run func(ctx context.Context, hash string)) *RefreshTokenRepository_FindByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RefreshTokenRepository_FindByHash_Call) Return(refreshToken *model.RefreshToken, err error) *RefreshTokenRepository_FindByHash_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *RefreshTokenRepository_FindByHash_Call) RunAndReturn(run func(ctx context.Context, hash string) (*model.RefreshToken, error)) *RefreshTokenRepository_FindByHash_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeByHash provides a mock function for the type RefreshTokenRepository
func (_mock *RefreshTokenRepository) RevokeByHash(ctx context.Context, hash string) error {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for RevokeByHash")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RefreshTokenRepository_RevokeByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeByHash'
type RefreshTokenRepository_RevokeByHash_Call struct {
	*mock.Call
}

// RevokeByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *RefreshTokenRepository_Expecter) RevokeByHash(ctx interface{}, hash interface{}) *RefreshTokenRepository_RevokeByHash_Call {
	return &RefreshTokenRepository_RevokeByHash_Call{Call: _e.mock.On("RevokeByHash", ctx, hash)}
}

func (_c *RefreshTokenRepository_RevokeByHash_Call) Run(run func(ctx context.Context, hash string)) *RefreshTokenRepository_RevokeByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RefreshTokenRepository_RevokeByHash_Call) Return(err error) *RefreshTokenRepository_RevokeByHash_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RefreshTokenRepository_RevokeByHash_Call) RunAndReturn(run func(ctx context.Context, hash string) error) *RefreshTokenRepository_RevokeByHash_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllForUser provides a mock function for the type RefreshTokenRepository
func (_mock *RefreshTokenRepository) RevokeAllForUser(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllForUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

type RefreshTokenRepository_RevokeAllForUser_Call struct {
	*mock.Call
}

func (_e *RefreshTokenRepository_Expecter) RevokeAllForUser(ctx interface{}, userID interface{}) *RefreshTokenRepository_RevokeAllForUser_Call {
	return &RefreshTokenRepository_RevokeAllForUser_Call{Call: _e.mock.On("RevokeAllForUser", ctx, userID)}
}

func (_c *RefreshTokenRepository_RevokeAllForUser_Call) Return(err error) *RefreshTokenRepository_RevokeAllForUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RefreshTokenRepository_RevokeAllForUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *RefreshTokenRepository_RevokeAllForUser_Call {
	_c.Call.Return(run)
	return _c
}

// Rotate provides a mock function for the type RefreshTokenRepository
func (_mock *RefreshTokenRepository) Rotate(ctx context.Context, oldToken uuid.UUID, newToken *model.RefreshToken) error {
	ret := _mock.Called(ctx, oldToken, newToken)

	if len(ret) == 0 {
		panic("no return value specified for Rotate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.RefreshToken) error); ok {
		r0 = returnFunc(ctx, oldToken, newToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RefreshTokenRepository_Rotate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rotate'
type RefreshTokenRepository_Rotate_Call struct {
	*mock.Call
}

// Rotate is a helper method to define mock.On call
//   - ctx context.Context
//   - oldToken uuid.UUID
//   - newToken *model.RefreshToken
func (_e *RefreshTokenRepository_Expecter) Rotate(ctx interface{}, oldToken interface{}, newToken interface{}) *RefreshTokenRepository_Rotate_Call {
	return &RefreshTokenRepository_Rotate_Call{Call: _e.mock.On("Rotate", ctx, oldToken, newToken)}
}

func (_c *RefreshTokenRepository_Rotate_Call) Run(run func(ctx context.Context, oldToken uuid.UUID, newToken *model.RefreshToken)) *RefreshTokenRepository_Rotate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *model.RefreshToken
		if args[2] != nil {
			arg2 = args[2].(*model.RefreshToken)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RefreshTokenRepository_Rotate_Call) Return(err error) *RefreshTokenRepository_Rotate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RefreshTokenRepository_Rotate_Call) RunAndReturn(run func(ctx context.Context, oldToken uuid.UUID, newToken *model.RefreshToken) error) *RefreshTokenRepository_Rotate_Call {
	_c.Call.Return(run)
	return _c
}
