// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"fyp/food-rs/types/model"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

type UserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepository) EXPECT() *UserRepository_Expecter {
	return &UserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type UserRepository
func (_mock *UserRepository) Create(ctx context.Context, data *model.User) (*model.User, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.User) (*model.User, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.User) *model.User); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.User) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - data *model.User
func (_e *UserRepository_Expecter) Create(ctx interface{}, data interface{}) *UserRepository_Create_Call {
	return &UserRepository_Create_Call{Call: _e.mock.On("Create", ctx, data)}
}

func (_c *UserRepository_Create_Call) Run(run func(ctx context.Context, data *model.User)) *UserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.User
		if args[1] != nil {
			arg1 = args[1].(*model.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepository_Create_Call) Return(user *model.User, err error) *UserRepository_Create_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserRepository_Create_Call) RunAndReturn(run func(ctx context.Context, data *model.User) (*model.User, error)) *UserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function for the type UserRepository
func (_mock *UserRepository) FindByEmail(ctx context.Context, email string) (*model.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type UserRepository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserRepository_Expecter) FindByEmail(ctx interface{}, email interface{}) *UserRepository_FindByEmail_Call {
	return &UserRepository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email)}
}

func (_c *UserRepository_FindByEmail_Call) Run(run func(ctx context.Context, email string)) *UserRepository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepository_FindByEmail_Call) Return(user *model.User, err error) *UserRepository_FindByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserRepository_FindByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*model.User, error)) *UserRepository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type UserRepository
func (_mock *UserRepository) FindByID(ctx context.Context, id uuid.UUID) (*model.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type UserRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *UserRepository_Expecter) FindByID(ctx interface{}, id interface{}) *UserRepository_FindByID_Call {
	return &UserRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *UserRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *UserRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepository_FindByID_Call) Return(user *model.User, err error) *UserRepository_FindByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*model.User, error)) *UserRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOnboardingStatus provides a mock function for the type UserRepository
func (_mock *UserRepository) UpdateOnboardingStatus(ctx context.Context, id uuid.UUID, completed bool) error {
	ret := _mock.Called(ctx, id, completed)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOnboardingStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) error); ok {
		r0 = returnFunc(ctx, id, completed)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRepository_UpdateOnboardingStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOnboardingStatus'
type UserRepository_UpdateOnboardingStatus_Call struct {
	*mock.Call
}

// UpdateOnboardingStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - completed bool
func (_e *UserRepository_Expecter) UpdateOnboardingStatus(ctx interface{}, id interface{}, completed interface{}) *UserRepository_UpdateOnboardingStatus_Call {
	return &UserRepository_UpdateOnboardingStatus_Call{Call: _e.mock.On("UpdateOnboardingStatus", ctx, id, completed)}
}

func (_c *UserRepository_UpdateOnboardingStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, completed bool)) *UserRepository_UpdateOnboardingStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserRepository_UpdateOnboardingStatus_Call) Return(err error) *UserRepository_UpdateOnboardingStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRepository_UpdateOnboardingStatus_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, completed bool) error) *UserRepository_UpdateOnboardingStatus_Call {
	_c.Call.Return(run)
	return _c
}
