all: false
dir: internal/mocks
pkgname: mocks
structname: "{{.InterfaceName}}"
filename: "{{ snakecase .InterfaceName }}.go"
template: testify

packages:
  fyp/food-rs/internal/interfaces:
    interfaces:
      UserRepository:
      PreferenceRepository:
      RefreshTokenRepository:
      CustomMealRepository:
      CustomMealService:
      CatalogService:
      AuthService:
      FoodSearcher:
      MealGenerator:
      PreferenceService:
      RecommendationService:
      CustomMealAutocompleter:
      FoodCandidateSearcher:
      MealMatchAdjudicator:
