import {
  ActionIcon,
  Alert,
  Badge,
  Box,
  Button,
  Group,
  Loader,
  Modal,
  NumberInput,
  Select,
  SegmentedControl,
  SimpleGrid,
  Stack,
  Text,
  TextInput,
  Title,
} from '@mantine/core'
import axios from 'axios'
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { useSearchParams } from 'react-router-dom'

import type { 
  MealLogItem, 
  MealLogMonthResponse, 
  MealLogReportResponse,
  MealLogType,
  MealLogUpdateInput,
} from './mealLogTypes'
import {
  fromDateTimeLocalValue,
  formatKcal,
  getCurrentDateTimeLocalValue,
  formatMealTime,
  formatMealType,
  formatMonthTitle,
  formatRM,
  getDefaultReportWeekRangeForMonth,
  getMonthDateRange,
  getNextMonthKey,
  getPreviousMonthKey,
  groupLogsByDay,
  parseDateKey,
  shiftDateKeyByDays,
  sumCalories,
  sumPrice,
  toDateTimeLocalValue,
  toMonthKey,
} from './mealLogHelpers'
import './MealLogPage.css'
import { FiCheck } from 'react-icons/fi'
import MealLogReportPanel from './MealLogReportPanel'
import { ChevronLeft, ChevronRight, Pencil, Trash2 } from 'lucide-react'
import MainNav from '@/theme/MainNav'
import { modalContentClassName, modalTransitionProps } from '@/theme/modalTransitions'


const mealTypeOptions = [
  { value: 'breakfast', label: 'Breakfast' },
  { value: 'lunch', label: 'Lunch' },
  { value: 'dinner', label: 'Dinner' },
  { value: 'other', label: 'Other' },
]

type ReportPeriodMode = 'month' | 'week'

export default function MealLogPage() {
  // State
  const [searchParams, setSearchParams] = useSearchParams()
  const hasAutoGeneratedReport = useRef(false)
  const [month, setMonth] = useState(() => toMonthKey(new Date()))
  const defaultReportWeekRange = useMemo(
    () => getDefaultReportWeekRangeForMonth(month),
    [month],
  )
  const [data, setData] = useState<MealLogMonthResponse | null>(null)
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [successMessage, setSuccessMessage] = useState<string | null>(null)
  const [editingLog, setEditingLog] = useState<MealLogItem | null>(null)
  const [deletingLog, setDeletingLog] = useState<MealLogItem | null>(null)
  const [editPrice, setEditPrice] = useState<number | ''>('')
  const [editEatenAt, setEditEatenAt] = useState('')
  const [editMealType, setEditMealType] = useState<MealLogType>('other')
  const [editError, setEditError] = useState<string | null>(null)
  const [deleteError, setDeleteError] = useState<string | null>(null)
  const [isSavingEdit, setIsSavingEdit] = useState(false)
  const [isDeleting, setIsDeleting] = useState(false)

  const [report, setReport] = useState<MealLogReportResponse | null>(null)
  const [reportPeriod, setReportPeriod] = useState<ReportPeriodMode>('month')
  const [reportWeekStart, setReportWeekStart] = useState(defaultReportWeekRange.start)
  const [reportWeekEnd, setReportWeekEnd] = useState(defaultReportWeekRange.end)
  const [isReportOpen, setIsReportOpen] = useState(false)
  const [isReportLoading, setIsReportLoading] = useState(false)
  const [reportError, setReportError] = useState<string | null>(null)

  const generateReport = useCallback(async () => {
    const token = localStorage.getItem('token')

    setIsReportLoading(true)
    setReportError(null)

    try {
      const response = await axios.get<MealLogReportResponse>(
        "/meal-logs/report",
        {
          params: reportPeriod === 'week'
            ? { period: reportPeriod, month, weekStart: reportWeekStart, weekEnd: reportWeekEnd }
            : { period: reportPeriod, month },
          headers: {
            Authorization: `Bearer ${token}`,
          }
        }
      )

      setReport(response.data)
      setIsReportOpen(true)

    } catch (error) {
      console.error('Failed to generate meal report', error)
      setReportError('Could not generate meal report')
    } finally {
      setIsReportLoading(false)
    }
  }, [month, reportPeriod, reportWeekStart, reportWeekEnd])

  useEffect(() => {
    setReport(null)
    setIsReportOpen(false)
    setReportError(null)
  }, [month, reportPeriod, reportWeekStart, reportWeekEnd])

  useEffect(() => {
    const nextWeekRange = getDefaultReportWeekRangeForMonth(month)
    setReportWeekStart(nextWeekRange.start)
    setReportWeekEnd(nextWeekRange.end)
  }, [month])

  const loadLogs = useCallback(async (signal?: AbortSignal) => {
    const token = localStorage.getItem('token')

    setIsLoading(true)
    setError(null)

    try {
      const response = await axios.get<MealLogMonthResponse>(
        "/meal-logs",
        {
          params: { month },
          headers: {
            Authorization: `Bearer ${token}`,
          },
          signal,
        },
      )

      setData(response.data)
    } catch (error) {
      if (axios.isCancel(error)) {
        return
      }

      console.error('Failed to load meal logs', error)
      setError('Could not load meal logs')
    } finally {
      if (!signal?.aborted) {
        setIsLoading(false)
      }
    }
  }, [month])

  // Fetch
  useEffect(() => {
    const request = new AbortController()

    void loadLogs(request.signal)

    return () => request.abort()
  }, [loadLogs])

  useEffect(() => {
    if (!successMessage) {
      return
    }

    const dismissTimer = window.setTimeout(() => {
      setSuccessMessage(null)
    }, 4000)

    return () => window.clearTimeout(dismissTimer)
  }, [successMessage])

  const openEditModal = (item: MealLogItem) => {
    setEditingLog(item)
    setEditPrice(item.price)
    setEditEatenAt(toDateTimeLocalValue(new Date(item.eatenAt)))
    setEditMealType(item.mealType)
    setEditError(null)
  }

  const closeEditModal = () => {
    if (isSavingEdit) {
      return
    }

    setEditingLog(null)
    setEditError(null)
  }

  const saveEditedLog = async () => {
    if (!editingLog) {
      return
    }

    if (editPrice === '' || Number(editPrice) < 0) {
      setEditError('Please enter a valid price')
      return
    }

    if (!editEatenAt) {
      setEditError('Please choose when you ate this meal')
      return
    }

    if (new Date(editEatenAt) > new Date()) {
      setEditError('Meal time cannot be in the future')
      return
    }

    const token = localStorage.getItem('token')
    const payload: MealLogUpdateInput = {
      price: Number(editPrice),
      eatenAt: fromDateTimeLocalValue(editEatenAt),
      mealType: editMealType,
    }

    setIsSavingEdit(true)
    setEditError(null)

    try {
      await axios.patch(`/meal-logs/${editingLog.id}`, payload, {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      })

      setEditingLog(null)
      setSuccessMessage(`${editingLog.mealName} updated`)
      await loadLogs()

      if (report) {
        await generateReport()
      }
    } catch (error) {
      console.error('Failed to update meal log', error)
      setEditError('Could not update this meal log')
    } finally {
      setIsSavingEdit(false)
    }
  }

  const openDeleteModal = (item: MealLogItem) => {
    setDeletingLog(item)
    setDeleteError(null)
  }

  const closeDeleteModal = () => {
    if (isDeleting) {
      return
    }

    setDeletingLog(null)
    setDeleteError(null)
  }

  const deleteLog = async () => {
    if (!deletingLog) {
      return
    }

    const token = localStorage.getItem('token')

    setIsDeleting(true)
    setDeleteError(null)

    try {
      await axios.delete(`/meal-logs/${deletingLog.id}`, {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      })

      setDeletingLog(null)
      setSuccessMessage(`${deletingLog.mealName} deleted`)
      await loadLogs()

      if (report) {
        await generateReport()
      }
    } catch (error) {
      console.error('Failed to delete meal log', error)
      setDeleteError('Could not delete this meal log')
    } finally {
      setIsDeleting(false)
    }
  }

  const groupedLogs = useMemo(() => {
    return groupLogsByDay(data?.items ?? [])
  }, [data])

  const dayEntries = (Object.entries(groupedLogs) as Array<[string, MealLogItem[]]>).sort(
    ([left], [right]) => Number(right) - Number(left),
  )
  const reportMonthRange = useMemo(() => getMonthDateRange(month), [month])
  const canGenerateReport = (data?.items.length ?? 0) > 0
  const canGenerateSelectedReport =
    reportPeriod === 'week'
      ? reportWeekStart.length > 0 && reportWeekEnd.length > 0
      : canGenerateReport

  useEffect(() => {
    if (
      searchParams.get('report') !== '1' ||
      hasAutoGeneratedReport.current ||
      isLoading ||
      !data
    ) {
      return
    }

    hasAutoGeneratedReport.current = true

    if (!canGenerateReport) {
      window.setTimeout(() => {
        setReportError('Add at least one meal log for this month to generate a report.')
      }, 0)
      setSearchParams({}, { replace: true })
      return
    }

    window.setTimeout(() => {
      void generateReport()
    }, 0)
    setSearchParams({}, { replace: true })
  }, [
    canGenerateReport,
    data,
    generateReport,
    isLoading,
    searchParams,
    setSearchParams,
  ])

  const clampReportDateToSelectedMonth = (value: string) => {
    if (!value) return value
    if (parseDateKey(value) < parseDateKey(reportMonthRange.start)) return reportMonthRange.start
    if (parseDateKey(value) > parseDateKey(reportMonthRange.end)) return reportMonthRange.end
    return value
  }

  const updateReportWeekStart = (value: string) => {
    value = clampReportDateToSelectedMonth(value)
    setReportWeekStart(value)

    if (!value || !reportWeekEnd || parseDateKey(reportWeekEnd) < parseDateKey(value)) {
      setReportWeekEnd(value)
      return
    }

    const maxEnd = shiftDateKeyByDays(value, 6)
    if (parseDateKey(reportWeekEnd) > parseDateKey(maxEnd)) {
      setReportWeekEnd(maxEnd)
    }
  }

  const updateReportWeekEnd = (value: string) => {
    value = clampReportDateToSelectedMonth(value)
    setReportWeekEnd(value)

    if (!value || !reportWeekStart || parseDateKey(value) < parseDateKey(reportWeekStart)) {
      setReportWeekStart(value)
      return
    }

    const minStart = shiftDateKeyByDays(value, -6)
    if (parseDateKey(reportWeekStart) < parseDateKey(minStart)) {
      setReportWeekStart(minStart)
    }
  }

  const shiftReportWeekRange = (days: number) => {
    const nextStart = shiftDateKeyByDays(reportWeekStart, days)
    const nextEnd = shiftDateKeyByDays(reportWeekEnd, days)

    if (
      parseDateKey(nextStart) < parseDateKey(reportMonthRange.start) ||
      parseDateKey(nextEnd) > parseDateKey(reportMonthRange.end)
    ) {
      return
    }

    setReportWeekStart(nextStart)
    setReportWeekEnd(nextEnd)
  }

  return (
    <Box className='ui-settings-page ui-meal-log-page'>
      {successMessage && (
        <Box
          className="ui-meal-log-success-toast"
          role="status"
          aria-live="polite"
        >
          <FiCheck className="ui-success-toast-icon" aria-hidden="true" />
          
          <Text fw={900}>{successMessage}</Text>
        </Box>
      )}

      <Box component="main" className='ui-settings-frame'>
        <MainNav active="logs" />

        <Box component="section" className='ui-meal-log-shell ui-surface'>
          <Group className="ui-meal-log-monthbar" justify="space-between">
            <Button
              variant="subtle"
              className='ui-meal-log-button'
              onClick={() => setMonth(getPreviousMonthKey(month))}  
            >
              {'< Previous Month'}
            </Button>

            <Title order={1}>Meal Log - {formatMonthTitle(month)}</Title>

            <Button
              variant="subtle"
              className="ui-meal-log-button"
              onClick={() => setMonth(getNextMonthKey(month))}
            >{'> Next Month'}</Button>
          </Group>

          {error && <Alert color="red">{error}</Alert>}

          {isLoading && (
            <Box className='ui-meal-log-loading'>
              <Loader color='green' />
              <Text fw={900}>Loading meal logs...</Text>
            </Box>
          )}

          {!isLoading && data && (
            <>
              <SimpleGrid cols={{ base: 2, md: data?.summary.showBudgetRemaining ? 4 : 3}} className='ui-meal-log-summary'>
                <Box>
                  <Text>Total Meals</Text>
                  <strong>{data.summary.totalMealsEaten}</strong>
                </Box>

                <Box>
                  <Text>Total Spent</Text>
                  <strong>{formatRM(data.summary.totalSpent)}</strong>
                </Box>
                
                <Box>
                  <Text>Total Calories</Text>
                  <strong>{formatKcal(data.summary.totalCalories)}</strong>
                </Box>
                {data.summary.showBudgetRemaining && (
                  <Box>
                    <Text>Budget Remaining</Text>
                    <strong className='ui-meal-log-budget'>
                      {formatRM(data.summary.budgetRemaining ?? 0)}
                    </strong>
                  </Box>
                )}
              </SimpleGrid>

              <Group justify="space-between" className="ui-meal-log-report-actions">
                <Box>
                  <Text fw={900}>{reportPeriod === 'week' ? 'Weekly report' : 'Monthly report'}</Text>
                  {reportPeriod === 'month' && data.items.length === 0 && (
                    <Text size="sm" className="ui-field-copy">
                      Add at least one meal log for this month to generate a report.
                    </Text>
                  )}
                  {reportError && (
                    <Text size="sm" c="red" fw={800}>
                      {reportError}
                    </Text>
                  )}
                </Box>

                <Group className="ui-meal-log-report-controls" gap="sm">
                  <SegmentedControl
                    className="ui-meal-log-report-period-toggle"
                    value={reportPeriod}
                    onChange={(value) => setReportPeriod(value as ReportPeriodMode)}
                    data={[
                      { value: 'month', label: 'Month' },
                      { value: 'week', label: 'Week' },
                    ]}
                  />

                  {reportPeriod === 'week' && (
                    <Group className="ui-meal-log-report-week-range" gap={6}>
                      <ActionIcon
                        variant="subtle"
                        className="ui-meal-log-report-week-shift"
                        aria-label="Previous week"
                        onClick={() => shiftReportWeekRange(-7)}
                      >
                        <ChevronLeft size={16} />
                      </ActionIcon>

                      <TextInput
                        className="ui-meal-log-report-week-input"
                        type="date"
                        aria-label="Weekly report start date"
                        value={reportWeekStart}
                        min={reportMonthRange.start}
                        max={reportMonthRange.end}
                        onChange={(event) => updateReportWeekStart(event.currentTarget.value)}
                        classNames={{
                          input: 'ui-input',
                        }}
                      />

                      <Text size="sm" className="ui-meal-log-report-week-separator">to</Text>

                      <TextInput
                        className="ui-meal-log-report-week-input"
                        type="date"
                        aria-label="Weekly report end date"
                        value={reportWeekEnd}
                        min={reportMonthRange.start}
                        max={reportMonthRange.end}
                        onChange={(event) => updateReportWeekEnd(event.currentTarget.value)}
                        classNames={{
                          input: 'ui-input',
                        }}
                      />

                      <ActionIcon
                        variant="subtle"
                        className="ui-meal-log-report-week-shift"
                        aria-label="Next week"
                        onClick={() => shiftReportWeekRange(7)}
                      >
                        <ChevronRight size={16} />
                      </ActionIcon>
                    </Group>
                  )}

                  <Button
                    className="ui-primary-button"
                    loading={isReportLoading}
                    disabled={!canGenerateSelectedReport}
                    onClick={generateReport}
                  >
                    Generate report
                  </Button>
                </Group>
              </Group>

              {report && (
                <MealLogReportPanel 
                  report={report}
                  isOpen={isReportOpen}
                  onToggle={() => setIsReportOpen((open) => !open)}
                />
              )}

              <Box className='ui-meal-log-divider' />

              {data.items.length === 0 ? (
                <Box className='ui-meal-log-empty'>
                  <Text fw={900}>No meals logged for this month</Text>
                  <Text className='ui-field-copy'>Meals you log from recommendations or search will appear here.</Text>
                </Box>
              ) : (
                <Box className='ui-meal-log-days'>
                  {dayEntries.map(([day, items]) => {
                    const [year, monthNumber] = month.split('-').map(Number)

                    const weekday = new Date(
                      year,
                      monthNumber - 1,
                      Number(day),
                    ).toLocaleDateString('en-US', {
                      weekday: 'short',
                    })

                    return(
                    <Box className='ui-meal-log-day' key={day}>
                      <Box className='ui-meal-log-day-header'>
                        <Box style={{
                          display: 'flex',
                          alignItems: 'center',
                          gap: '8px',
                        }}>
                        <Text fw={900} style={{fontSize: 20}}>{String(day).padStart(2, '0')}</Text>
                        <Badge variant='light' color='rgb(231, 139, 0)'>
                          {weekday}
                        </Badge>
                        </Box>
                        <Text></Text>
                        <Text fw={900} style={{textAlign: 'right'}}>{formatKcal(sumCalories(items))}</Text>
                        <Text fw={900} style={{textAlign: 'right'}}>{formatRM(sumPrice(items))}</Text>
                        <Text className="ui-meal-log-actions-heading" aria-hidden="true"></Text>
                      </Box>

                      {items.map((item) => (
                        <Box className='ui-meal-log-row' key={item.id}>
                          <Text>{formatMealTime(item.eatenAt)}</Text>
                          <Box>
                            <Text fw={900}>{item.mealName}</Text>
                            <Text size="xs" className="ui-field-copy">{formatMealType(item.mealType)}</Text>
                          </Box>
                          <Text>{formatKcal(item.calories)}</Text>
                          <Text>{formatRM(item.price)}</Text>
                          <Group className="ui-meal-log-row-actions" gap={6} justify="flex-end">
                            <ActionIcon
                              aria-label={`Edit ${item.mealName}`}
                              variant="subtle"
                              size="sm"
                              className="ui-meal-log-action-button"
                              onClick={() => openEditModal(item)}
                            >
                              <Pencil />
                            </ActionIcon>

                            <ActionIcon
                              aria-label={`Delete ${item.mealName}`}
                              variant="subtle"
                              color="red"
                              size="sm"
                              className="ui-meal-log-action-button ui-meal-log-delete-button"
                              onClick={() => openDeleteModal(item)}
                            >
                              <Trash2 />
                            </ActionIcon>
                          </Group>
                        </Box>
                      ))}
                    </Box>
                    )
                  })}
                </Box>
              )}
            </>
          )}
        </Box>
      </Box>

      <Modal
        opened={editingLog !== null}
        onClose={closeEditModal}
        transitionProps={modalTransitionProps}
        centered
        title="Edit meal log"
        classNames={{
          content: modalContentClassName('ui-meal-log-modal'),
          title: 'ui-meal-log-modal-title',
        }}
      >
        {editingLog && (
          <Stack gap="md">
            <Stack gap={4}>
              <Text fw={900} style={{fontSize: 24}}>{editingLog.mealName}</Text>
              <Text size="sm" c="dimmed">{formatKcal(editingLog.calories)}</Text>
            </Stack>

            {editError && <Text c="red" fw={800}>{editError}</Text>}

            <NumberInput
              label="Price (RM)"
              min={0}
              clampBehavior='none'
              decimalScale={2}
              value={editPrice}
              onChange={(value) => setEditPrice(value === '' ? '' : Number(value))}
              classNames={{ input: 'ui-input'}}
            />

            <TextInput
              label="Time eaten"
              type="datetime-local"
              value={editEatenAt}
              onChange={(event) => setEditEatenAt(event.currentTarget.value)}
              classNames={{ input: 'ui-input'}}
              max={getCurrentDateTimeLocalValue()}
            />

            <Select
              label="Meal type"
              data={mealTypeOptions}
              value={editMealType}
              onChange={(value) => setEditMealType((value ?? 'other') as MealLogType)}
              classNames={{ input: 'ui-input' }}
              allowDeselect={false}
            />

            <Group justify="flex-end">
              <Button variant="subtle" onClick={closeEditModal} disabled={isSavingEdit}>
                Cancel
              </Button>
              <Button className="ui-primary-button" loading={isSavingEdit} onClick={saveEditedLog}>
                Save changes
              </Button>
            </Group>
          </Stack>
        )}
      </Modal>

      <Modal
        opened={deletingLog !== null}
        onClose={closeDeleteModal}
        transitionProps={modalTransitionProps}
        centered
        title="Delete meal log"
        classNames={{
          content: modalContentClassName('ui-meal-log-modal'),
          title: 'ui-meal-log-modal-title',
        }}
      >
        {deletingLog && (
          <Stack gap="md">
            <Text>
              Delete <strong>{deletingLog.mealName}</strong> from your meal log?
            </Text>

            {deleteError && <Text c="red" fw={800}>{deleteError}</Text>}

            <Group justify="flex-end">
              <Button variant="subtle" onClick={closeDeleteModal} disabled={isDeleting}>
                Cancel
              </Button>
              <Button color="red" loading={isDeleting} onClick={deleteLog}>
                Delete
              </Button>
            </Group>
          </Stack>
        )}
      </Modal>
    </Box>
  )
}
